name: complet_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  retrofit_generator: ^8.1.0
  json_annotation: ^4.9.0
  get_it: ^7.6.7
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  pretty_dio_logger: ^1.3.1
  easy_localization: ^3.0.7
  intl: ^0.18.1
  flutter_native_splash: ^2.3.11
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

